### ISSUE TITLE
De 1e visualisatie (bewoners) iets hoger maken

### ISSUE THREAD

**Issue by ErikNijland** [DatapuntAmsterdam/bbga_visualisatie_d3#12]
Omdat anders letters aan de onderkant, van de legenda, buiten beeld vallen, zoals de g bij Grachtengordel.

**Comment by kerkuil** [comment]
Opgelost met commit ffcad839099ea697eacff6aff80521e1889c7e58

**Comment by ErikNijland** [comment]
Ik ga de build 'aanslingeren' over een kwartiertje staat dit op acceptatie.
