### ISSUE TITLE
[Tevredenheid] Rood van het icoon is donkerder dan de andere rood

### ISSUE THREAD

**Issue by kerkuil** [DatapuntAmsterdam/bbga_visualisatie_d3#13]

**Comment by ErikNijland** [comment]
De huisjes bij de taartdiagram en het icoon bij tevredenheid hebben op dit moment (ik heb geen aanpassingen gedaan) dezelfde kleur. Namelijk: #eb2227. De iconen bij de staafdiagram/bewoners hebben een andere kleur rood. Namelijk: #f00.

Als het anders moet dan graag ook het huizen icoon in dezelfde kleur maken. Voor nu laat ik het even zoals het is. Het lijkt namelijk op een bewuste keuze van Erna.

**Comment by kerkuil** [comment]
> De huisjes bij de taartdiagram en het icoon bij tevredenheid hebben op dit moment (ik heb geen aanpassingen gedaan) dezelfde kleur. Namelijk: #eb2227.

De huisjes hebben geen embedded kleur. Die had ik al er uit gesloopt. Ze worden hier van de verkeerde kleur voorzien. Dat was inderdaad een foutje van mij:
https://github.com/DatapuntAmsterdam/bbga_visualisatie_d3/blob/master/bbga.css#L169-L171

> Als het anders moet dan graag ook het huizen icoon in dezelfde kleur maken. Voor nu laat ik het even zoals het is. Het lijkt namelijk op een bewuste keuze van Erna.

Dat is het niet, want ik heb het er natuurlijk met Erna over gehad. De huizen moeten dus aangepast worden. Zorg jij dat zowel de huizen als het tevredenheid icoon beide rood worden?

**Comment by ErikNijland** [comment]
is opgelost, gaat vanavond mee naar productie
