### ISSUE TITLE
Sommige waardes zijn 0 of null

### ISSUE THREAD

**Issue by ErikNijland** [DatapuntAmsterdam/bbga_visualisatie_d3#2]
Voorbeeld buurt: Rietland Oost (code: M51a)

- In sommige buurten zijn geen corporatie woningen; je krijgt dan het getal 0 als waarde.
- Soms is de prijs per m2 niet bekend; je krijgt dan de waarde null.

Todo: de code herzien met de aanname dat alle variabelen optioneel zijn.

![voorbeeld_waarde_0_en_null](https://cloud.githubusercontent.com/assets/7983484/15391812/a73a4bfa-1dc3-11e6-99f8-7214d85b6123.png)

**Comment by ErikNijland** [comment]
Dit probleem speelt ook bij deze buurt: Amstel III deel C/D Noord (code: T92c). Hier is mist alle informatie voor de taartdiagram. En ook daar is de prijs per m2 onbekend. Enkel de prijs per m2 voor Amsterdam is daar gevuld.

**Comment by kerkuil** [comment]
@ivierv gaat even na hoe dit in de data zelf zit? 

Vraag is ook of we daarbij de legende onderdelen moeten weglaten waar geen data van is mits er van een van de categorieën wel data is. Als ze allemaal missen, dan kunnen we de taart drieën delen en als waardes "onbekend" o.i.d. neerzetten.

**Comment by ivierv** [comment]
De opmerkingen van @ErikNijland over de data kloppen: 0 geeft aan dat er wel een gegeven bekend is, maar dat het niet aanwezig is in een gebied. Null geeft aan dat er over dat gebied geen gegeven bekend is.

Ik zou er zelf voor kiezen om in het geval van onbekend de donut in één kleur te laten, en 1 legenda element met titel 'onbekend'. Als je 'm in drieën verdeelt wek je de illusie dat er een evenredige verdeling is, terwijl er geen gegevens bekend zijn. 

Wat betreft 1 categorie wel bekend, en rest niet: dit komt niet voor. Of er is helemaal geen data over het gebied, of alles is bekend.

**Comment by kerkuil** [comment]
> Wat betreft 1 categorie wel bekend, en rest niet: dit komt niet voor. Of er is helemaal geen data over het gebied, of alles is bekend.

Terwijl in M51a maar twee categorieën bekend zijn? Dus twee bekend kan wel, maar één niet?

**Comment by ivierv** [comment]
In M51a is er geen sprake van onbekend, maar van niet aanwezig. Er zijn 0 corporatiewoningen, niet null. Ik bedoelde dat of alle 3 de categorieën op null staan, of alle 3 data bevatten.

Blijft natuurlijk het legenda issue. Ik zou er denk ik voor kiezen om dan wel alle legenda-items te laten staan.

**Comment by kerkuil** [comment]
Mijn idee zou zijn om in geval van allemaal onbekend de taart in drieën te delen en dan als percentage in de taartdelen `onb.` te zetten.

**Comment by kerkuil** [comment]
Zou opgelost moeten zijn met fb4c6be5

**Comment by ErikNijland** [comment]
**Eerste visualisatie**
De waardes 0 en null worden allebei als 0 beschouwd. Dit klopt niet. Bij de waarde null weten we niet wat de waarde is.

**Tweede visualisatie**
![waardes_0_en_null](https://cloud.githubusercontent.com/assets/7983484/15496676/e87153c6-2196-11e6-8d8b-c04817ea74a5.png)

Ik heb de commit bekeken. In de taartdiagram. Als er geen woningen zijn (bv. op een industrieterrein). Dan hebben alle variabelen de waarde 0. In dit geval is het bekend dat er geen woningen zijn. In de taartdiagram zie ik echter een grijze kleur die overeenkomt met de kleur van corporatiewoningen. Nu lijkt het erop dat alle woningen van het type corporatiewoning zijn. In werkelijkheid zijn er helemaal geen huizen.

Als de waarde null is bij alle variabelen dan is dit wel een geschikte oplossing alleen is de kleur ongelukkig gekozen (want het lijkt op corporatiewoning). Bovendien verwacht ik voor een nieuwe kleur een vervangende legenda die aangeeft dat de waardes onbekend zijn.

Tot slot verschijnt de waarde null nog bij de prijs per m2. Daar verwacht ik de tekst 'onbekend' zonder Euroteken en 'geld notatie'.

**Comment by kerkuil** [comment]
> De waardes 0 en null worden allebei als 0 beschouwd. Dit klopt niet. Bij de waarde null weten we niet wat de waarde is.

Los ik op

> taartdiagram zie ik echter een grijze kleur die overeenkomt met de kleur van corporatiewoningen. Nu lijkt het erop dat alle woningen van het type corporatiewoning zijn. In werkelijkheid zijn er helemaal geen huizen.

De kleur is niet hetzelfde, maar lijkt hetzelfde. Ik overleg even met de vormgever hoe we dit oplossen.

> Bovendien verwacht ik voor een nieuwe kleur een vervangende legenda die aangeeft dat de waardes onbekend zijn. [...] Tot slot verschijnt de waarde null nog bij de prijs per m2. Daar verwacht ik de tekst 'onbekend' zonder Euroteken en 'geld notatie'.

Een vraagteken lijkt me het rustigst. Kijk maar even naar de laatste commit 2b436d8
