### ISSUE TITLE
De uitlijning van het huizen icoon

### ISSUE THREAD

**Issue by ErikNijland** [DatapuntAmsterdam/bbga_visualisatie_d3#3]
Het huizen icoon staat niet altijd gecentreerd. Bij sommige datasets staat het icoon te ver naar links of rechts. In sommige gevallen valt het icoon ook over de tekst van het percentage heen.

![huizen-icoon](https://cloud.githubusercontent.com/assets/7983484/15463322/debc1628-20c8-11e6-96f9-8ad7fdb317f0.png)

Dit is getest in Chrome.

**Comment by kerkuil** [comment]
En dat gebeurt ook standalone? Dus zonder integratie in atlas?

**Comment by ErikNijland** [comment]
Standalone gebeurd het ook; ik heb dit net gecontroleerd in de index.html van deze repository, zonder hierbij de voorbeeld data (uit de index.html) aan te passen.

**Comment by kerkuil** [comment]
Kan je kijken of dit bij fb4c6be5 nog zo is. Heb je anders voorbeeld getallen waarbij dit optreedt?

**Comment by ErikNijland** [comment]
Dit gaat nog steeds verkeerd. Ik heb een los HTML bestand gemaakt en gecommit met een andere dataset (om een ander issue te testen). En er zit verschil in de uitlijning bij deze twee HTML bestanden.

**Comment by kerkuil** [comment]
Hmm, specifiek chrome probleem terwijl ik voornamelijk in Firefox werk. Ik ga neuzen.

**Comment by kerkuil** [comment]
Moet nu opgelost zijn. Ik heb het geheel hardcoded.
