### ISSUE TITLE
Zinnetjes binnen grafieken opnemen

### ISSUE THREAD

**Issue by sraeymaekers** [DatapuntAmsterdam/bbga_visualisatie_d3#6]
Kunnen de algemene zinnetjes onder de grafiek meegenomen worden in de D3 grafieken?
Zie screenshots toegevoegd. 
Groetjes, Sophie
<img width="302" alt="schermafbeelding 2016-05-24 om 09 53 45" src="https://cloud.githubusercontent.com/assets/19533659/15496895/24ea336c-2198-11e6-9475-7b485b2b586a.png">
<img width="282" alt="schermafbeelding 2016-05-24 om 09 53 33" src="https://cloud.githubusercontent.com/assets/19533659/15496893/24d46bc2-2198-11e6-8b25-2614296f0ab9.png">
![Uploading Schermafbeelding 2016-05-24 om 09.53.40.png…]()

**Comment by kerkuil** [comment]
Geen aanhef a.u.b.

**Comment by sraeymaekers** [comment]
Ik heb mailtje gestuurd voor overleg, want ons lijkt dat juist niet zo handig om dat in de HTML op te nemen, juist omdat jullie graag de regie/controle willen behouden. Dan dient het op 2 plekken aangepast te worden, als er een wijziging nodig is.
