### ISSUE TITLE
Vraag: vormgeving zonder tabbladen

### ISSUE THREAD

**Issue by sraeymaekers** [DatapuntAmsterdam/bbga_visualisatie_d3#8]
Zie ook email, kunnen we de grafieken onder elkaar plaatsen zonder de tabbladen?
Tabbladen/herstructuring van atlas content is in volle gang.

Ik hoor het graag, dank je wel.

**Comment by ErikNijland** [comment]
Plus een subvraag: kan er in plaats van tabbladen anders misschien een header komen boven elke visualisatie?

**Comment by sraeymaekers** [comment]
Antwoord ontvangen van Maurice. Zal intern overlegd worden. Terugkoppeling volgt.

**Comment by kerkuil** [comment]
Graag zonder aanhef :wink:
